name: Screenshot tests all packages of Taiga UI

on:
  pull_request:
  push:
    branches:
      - '!master'

jobs:
  cy-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run screenshot tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          command: npm run test

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/snapshots
          retention-days: 7
